-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema psgamedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `psgamedb` ;

-- -----------------------------------------------------
-- Schema psgamedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `psgamedb` DEFAULT CHARACTER SET utf8 ;
USE `psgamedb` ;

-- -----------------------------------------------------
-- Table `game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game` ;

CREATE TABLE IF NOT EXISTS `game` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `image_url` VARCHAR(2000) NULL,
  `developer` VARCHAR(100) NULL,
  `rating` VARCHAR(45) NULL,
  `genre` VARCHAR(100) NULL,
  `metascore` INT NULL,
  `user_score` DOUBLE NULL,
  `publisher` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS player@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'player'@'localhost' IDENTIFIED BY 'player';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'player'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `game`
-- -----------------------------------------------------
START TRANSACTION;
USE `psgamedb`;
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Elden Ring', 'Summary: A New World Created By Hidetaka Miyazaki And George R. R. Martin. ELDEN RING, developed by FromSoftware, Inc. and BANDAI NAMCO Entertainment Inc., is a fantasy action-RPG adventure set within a world created by Hidetaka Miyazaki creator of the influential DARK SOULS video game series; and George R.R. Martin author of The New York Times best-selling fantasy series, A Song of Ice and Fire. Danger and discovery lurk around every corner in FromSoftware\'s largest game to-date. Hidetaka Miyazaki, President and Game Director of FromSoftware Inc. Known for directing critically-acclaimed games in beloved franchises including Armored Core, Dark Souls, and Sekiro: Shadows Die Twice. George R.R. Martin is the #1 New York Times bestselling author of many novels, including the acclaimed series A Song of Ice and Fire - A Game of Thrones, A Clash of Kings, A Storm of Swords, A Feast For Crows, and A Dance with Dragons. As a writer-producer, he has worked on The Twilight Zone, Beauty and the Beast, and various feature films and pilots that were never made.', 'https://static.metacritic.com/images/products/games/7/cf21bb68e9006d17f7b7bff4cdafe6f6-98.jpg', 'From Software', 'M', 'Action RPG', 96, 7.7, 'Bandai Namco Games');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, '\nThe Witcher 3: Wild Hunt', 'Summary: You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy, a living weapon that can alter the shape of the world. The Complete Edition contains the base game, offering a huge, over 100-hour long, open-world adventure, as well as both of its massive story expansions: Hearts of Stone & Blood and Wine worth an extra 50 hours of gameplay! It also comes with all additional content released for the game, alongside new features and items, including a built-in Photo Mode, swords, armor, and alternate outfits inspired by The Witcher Netflix series — and more!', 'https://static.metacritic.com/images/products/games/6/b69dbd7a51771cabc64436f218fe630b-98.jpg', 'CD Projekt Red Studio', 'M', 'Action RPG', 96, 7.4, 'CD Projekt Red Studio');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'God of War: Ragnarok', 'Summary: The freezing winds of Fimbulwinter have come to Midgard, making survival for Kratos, Atreus, and Mimir in the Norse wilds even more challenging than before. Kratos, still bearing the knowledge of his past mistakes, wants to spare Atreus the bloody lessons he learned from his conflict with gods. He wants to keep his son safe, above all, and their confrontation with Baldur has vindicated the belief that only tragedy will come from further entanglements with the Aesir. Together, Kratos and Atreus will have to make a choice about which path they will take. Whatever they choose will define the fate of all those living in the Nine Realms as Ragnarok approaches. Whatever your choice of combat strategy, the enemies that await in God of War Ragnarök will be ready. The realms have grown harsher, and a whole host of new creatures from across Norse mythology will test your skills. God of War Ragnarök will take you to the previously unreachable Vanaheim, Svartalfheim, and Asgard - as well as to new areas from locations featured in the last game. Exploring the realms will take you everywhere from verdant, otherworldly jungles to intricate subterranean mining networks. This next installment in the series will bring you a more diverse, beautiful, and mysterious variety of locations than in any other God of War game.', 'https://static.metacritic.com/images/products/games/4/f475a29eab99cd7823b8cf860df11335-98.jpg', 'SCE Sant Monica', 'M', 'Action Adventure', 94, 7.9, 'PlayStation Studios');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Hades', 'Summary: Defy the god of the dead as you hack and slash out of the Underworld in this rogue-like dungeon crawler from the creators of Bastion, Transistor, and Pyre. Hades is a god-like rogue-like dungeon crawler that combines the best aspects of Supergiant\'s critically acclaimed titles, including the fast-paced action of Bastion, the rich atmosphere and depth of Transistor, and the character-driven storytelling of Pyre. BATTLE OUT OF HELL. As the immortal Prince of the Underworld, you\'ll wield the powers and mythic weapons of Olympus to break free from the clutches of the god of the dead himself, while growing stronger and unraveling more of the story with each unique escape attempt.', 'https://static.metacritic.com/images/products/games/5/a66616196a10f5be40b1edfed3c61a54-98.jpg', 'Supergiant Games', 'T', 'Action Adventure', 93, 8.6, 'Private Division');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Demon\'s Souls', 'Summary: From PlayStation Studios and Bluepoint Games comes a remake of the PlayStation classic, Demon’s Souls. Entirely rebuilt from the ground up and masterfully enhanced, this remake introduces the horrors of a fog-laden, dark fantasy land to a whole new generation of gamers. Those who’ve faced its trials and tribulations before, can once again challenge the darkness in stunning visual quality and incredible performance. In his quest for power, the 12th King of Boletaria, King Allant channelled the ancient Soul Arts, awakening a demon from the dawn of time itself, The Old One. With the summoning of The Old One, a colorless fog swept across the land, unleashing nightmarish creatures that hungered for human souls. Those whose souls were stripped from them, lost their minds – left only with the desire to attack the sane that remained. Now, Boletaria is cut off from the outside world, and the knights who dare penetrate the deep fog to free the land from its plight, are never seen again. As a lone warrior who has braved the baneful fog, you must face the hardest of challenges to earn the title “Slayer of Demons” and send The Old One back to its slumber.', 'https://static.metacritic.com/images/products/games/7/1aa54a2d35e13b422ee8fcc40c1126fd-98.jpg', 'Bluepoint Games', 'M', 'Action RPG', 92, 8.0, 'PlayStation Studios');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Persona 5 Royal', 'Summary: Forced to transfer to a high school in Tokyo, the protagonist has a strange dream. \"You truly are a prisoner of fate. In the near future, ruin awaits you.\" With the goal of \"rehabilitation\" looming overhead, he must save others from distorted desires by donning the mask of a Phantom Thief.\nPrepare for an all-new RPG experience in Persona 5 Royal based in the universe of the award-winning series, Persona!\nDon the mask of Joker and join the Phantom Thieves of Hearts. Break free from the chains of modern society and stage grand heists to infiltrate the minds of the corrupt and make them change their ways! Persona 5 Royal is packed with new characters, confidants, story depth, new locations to explore, and a new grappling hook mechanic for stealthy access to new areas. With a new semester at Shujin Academy, get ready to strengthen your abilities in the metaverse and in your daily life.', 'https://static.metacritic.com/images/products/games/9/29de53248f9b0e7d6b450de56434f94a-98.jpg', 'Atlus', 'M', 'Role-Playing', 91, 7.4, 'Sega');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Tony Hawk\'s Pro Skater 1 + 2', 'Summary: Drop back in with the most iconic skateboarding games ever made. Play Tony Hawk\'s Pro Skater & Tony Hawk\'s Pro Skater 2 in one epic collection, rebuilt from the ground up in incredible HD. All the pro skaters, levels and tricks are back and fully-remastered, plus more.', 'https://static.metacritic.com/images/products/games/2/e3a81e9605fbb91df122277b8ba7c976-98.jpg', 'Vicarious Visions', 'T', 'Sports', 90, 7.2, 'Activision');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Final Fantasy XIV: Endwalker', 'Summary: Endwalker is the fourth expansion pack for FINAL FANTASY XIV Online. Experience the climax of the Hydaelyn and Zodiark story, and encounter an even greater calamity than ever before as you travel to the far reaches of Hydaelyn and even to the moon.', 'https://static.metacritic.com/images/products/games/7/e8159d7deef2e0ad60132484fa4f7bec-98.jpg', 'Square Enix', 'T', 'Role-Playing', 90, 90, 'Square Enix');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Final Fantasy VII Remake Intergrade', 'Summary: FINAL FANTASY VII REMAKE expands upon and reimagines the spectacular world of the original PlayStation game. It covers up through the escape from Midgar and is the first game in the FINAL FANTASY VII REMAKE project. INTERGRADE is a bundle that includes both REMAKE and the new episode featuring Yuffie. In her episode, play as the spirited ninja after she arrives in Midgar. There, she and another Wutaian operative are to rendezvous with Avalanche HQ, infiltrate the Shinra Building, and steal the conglomerate\'s most powerful materia.', 'https://static.metacritic.com/images/products/games/6/2b1c1c378846d0571fad0cd13ff0d718-98.jpg', 'Square Enix', 'T', 'Role-Playing', 89, 8.3, 'Square Enix');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'The Stanley Parable: Ultra Deluxe', 'Summary: The Stanley Parable: Ultra Deluxe is an expanded re-imagining of 2013\'s The Stanley Parable. You will play as Stanley, and you will not play as Stanley. You will make a choice, and you will become powerless. You are not here to win. The Stanley Parable is a game that plays you.', 'https://static.metacritic.com/images/products/games/2/134b3a23ec97cda768e5117382465596-98.jpg', 'Crows Crows Crows', 'E10+', 'Adventure', 89, 8.1, NULL);
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Disco Elysium: The Final Cut', 'Summary: Disco Elysium is about a detective who wakes up in a rundown coastal district with a banging headache and only a few dregs of memory left. You set out to discover what happened to him inside the unique world we have created. We’ve thrown together disco music, early motor carriages, and post-revolutionary angst for our setting, and brought it all to life with actual oil paintings.', 'https://static.metacritic.com/images/products/games/8/4b0ecf70b78ebf5b09b6a359b04174f3-98.jpg', 'ZA/UM', 'M', 'Role-Playing', 89, 7.9, 'ZA/UM');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Devil May Cry 5: Special Edition', 'Summary: Devil May Cry is back. The legendary stylish action game is better than ever in the ultimate version of this multi-award winning hit.', 'https://static.metacritic.com/images/products/games/2/c663decaabea81d97dce2750b5077d99-98.jpg', 'Capcom', 'M', 'Action Adventure', 89, 8.4, 'Capcom');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'The Last of Us Part 1', 'Summary: In a ravaged civilization, where infected and hardened survivors run rampant, Joel, a weary protagonist, is hired to smuggle 14-year-old Ellie out of a military quarantine zone. However, what starts as a small job soon transforms into a brutal cross-country journey. Includes the complete The Last of Us single-player story and celebrated prequel chapter, Left Behind, which explores the events that changed the lives of Ellie and her best friend Riley forever.', 'https://static.metacritic.com/images/products/games/0/e482c292d76eb52e010b35979f1366d2-98.jpg', 'Naughty Dog', 'M', 'Action Adventure', 88, 6.2, 'Sony Interactive Entertainment');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Ratchet & Clank: Rift Apart', 'Summary: Ratchet & Clank: Rift Apart is an intergalactic adventure from Insomniac Games that showcases what’s possible for games designed around PS5’s SSD and DualSense wireless controller. Players seamlessly travel through different dimensions in mid-gameplay. The DualSense wireless controller brings combat to life, with haptic feedback and the adaptive triggers adding powerful sensations that increase immersion in combat.', 'https://static.metacritic.com/images/products/games/1/55ecfef13c44fdf3f23d385d310a64e2-98.jpg', 'Insomniac Games', 'E10+', 'Action Platformer', 88, 8.5, 'PlayStation Studios');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'It Takes Two', 'Summary: From Hazelight comes It Takes Two an innovative co-op adventure where uniquely varied gameplay and emotional storytelling intertwine in a fantastical journey. Founded to push the creative boundaries of what\'s possible in games, Hazelight is the award-winning studio behind the critically acclaimed A Way Out and Brothers: A Tale of Two Sons.', 'https://static.metacritic.com/images/products/games/4/04a369bc682d4082251ea52cadc58dd9-98.jpg', 'Hazelight', 'T', 'Action Adventure', 88, 9.1, 'Electronic Arts');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Deathloop', 'Summary: If at first you don\'t succeed Die, Die Again. From the team at Arkane Lyon comes an innovative take on first-person action. \"DEATHLOOP\" transports players to the lawless island of Blackreef in an eternal struggle between two extraordinary assassins. Explore stunning environments and meticulously designed levels in an immersive gameplay experience that lets you approach every situation any way you like. Hunt down targets all over the island in an effort to put an end to the cycle once and for all, and remember, if at first you don\'t succeed die, die again.', 'https://static.metacritic.com/images/products/games/8/ed8d74c28c9f35ac37b809219c697848-98.jpg', 'Arkane Studios', 'M', 'Action Shooter', 88, 6.5, 'Bethesda Softworks');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Horizon Forbidden West', 'Summary: Join Aloy as she braves the Forbidden West – a majestic but dangerous frontier that conceals mysterious new threats. Explore distant lands, fight bigger and more awe-inspiring machines, and encounter astonishing new tribes as you return to the far-future, post-apocalyptic world of Horizon. The land is dying. Vicious storms and an unstoppable blight ravage the scattered remnants of humanity, while fearsome new machines prowl their borders. Life on Earth is hurtling towards another extinction, and no one knows why. It\'s up to Aloy to uncover the secrets behind these threats and restore order and balance to the world. Along the way, she must reunite with old friends, forge alliances with warring new factions and unravel the legacy of the ancient past – all the while trying to stay one step ahead of a seemingly undefeatable new enemy.', 'https://static.metacritic.com/images/products/games/9/4b2f5ab7b2de8a156a4fde6b39884ae2-98.jpg', 'Guerilla', 'T', 'Action Adventure', 88, 8.0, 'PlayStation Studios');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Mortal Kombat 11 Ultimate', 'Summary: Experience 2 robust and critically acclaimed story campaigns from Mk11 & Mk11: aftermath. Play as the complete 37-character roster including newly added fighters mileena, RaiN & rambo. Thousands of Skins & weapons & Gear for an unprecedented level of Fighter customization. Includes all previous guest fighters such as Terminator Joker spawn & robocop. Every mode included.', 'https://static.metacritic.com/images/products/games/7/288055089131e6daa4ffb4ed4eac72a7-98.jpg', 'NetherRealm Studios', 'M', 'Fighting', 88, 7.3, 'Warner Bros. Games');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Ghost of Tsushima: Director\'s Cut', 'Summary: Ghost of Tsushima Director\'s Cut includes: Ghost of Tsushima full game; Iki Island expansion: New story, mini-games, enemy types and more*; Legends online co-op mode; Downloadable content: Digital mini art book, Director\'s commentary, One Technique Point, Charm of Hachiman\'s Favor, Hero of Tsushima Skin Set. PS5 Features: Dynamic 4K resolution targeting 60fps (requires compatible 4K TV or display). DualSense™ wireless controller haptic feedback and adaptive trigger resistance. 3D Audio (with analog or USB stereo headphones). Lip sync for Japanese voiceover. Ability to transfer PS4 saved progress to PS5 game.', 'https://static.metacritic.com/images/products/games/1/db0384bd9e420751b7e0a06861a114c0-98.jpg', 'Sucker Punch', 'M', 'Action Adventure', 87, 7.3, 'PlayStation Studios');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'The Nioh Collection', 'Summary: Celebrate the franchise\'s 4-year anniversary with remastered editions of both games featuring 4K and up to 120FPS support.\nFor everyone that recently purchased the PlayStation 5 console, you will be able to experience the complete Nioh 2 adventure in Nioh 2 Remastered The Complete Edition, along with a remastered version of the first entry in the series: Nioh Remastered The Complete Edition. If you would like all of this content in one convenient place, we have the perfect title for all of your Nioh needs. Get ready to relive the entire series with all DLC included for both titles in The Nioh Collection for PlayStation 5.', 'https://static.metacritic.com/images/products/games/4/0eb530ee536c99241f85419ea8eda217-98.jpg', 'Team Ninja', 'M', 'Action RPG', 87, 8.0, 'Sony Interactive Entertainment');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Gran Turismo 7', 'Summary: From classic vehicles and tracks to the reintroduction of the legendary GT Simulation Mode – GT 7 brings together the best features from past installments of the series alongside the future. An even more realistic driving experience awaits thanks to haptic feedback, which brings to life what it’s like when the tires hit the road. PS5’s immersive 3D audio allows players to sense the position of other cars and drivers around them.', 'https://static.metacritic.com/images/products/games/0/fc2ed38cd981a47d38f24911317270a9-98.jpg', 'Polyphony Digital', 'E', 'Racing', 87, 2.1, 'PlayStation Studios');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Guilty Gear -Strive-', 'Summary: “Guilty Gear -Strive-“ is the latest entry in the Guilty Gear fighting game franchise. Created by Daisuke Ishiwatari and developed by Arc System Works, “Guilty Gear -Strive-“ upholds the series’ reputation for groundbreaking hybrid 2D/3D cell-shaded graphics and intense, rewarding gameplay. There is a fully voiced story mode diving deep into the Guilty Gear universe, new characters joining fan favorites, and robust rollback net code. The cutting-edge 2D/3D hybrid graphics pioneered in the Guilty Gear series have been raised to the next level in “Guilty Gear -Strive-“. The new artistic direction and improve character animations will go beyond anything you’ve seen before in a fighting game!', 'https://static.metacritic.com/images/products/games/7/2dd10b770056b3a891f89c3ca35cd3f3-98.jpg', 'Arc System Works', 'T', 'Fighting', 87, 7.7, 'Arc System Works');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Uncharted: Legacy of Thieves Collection', 'Summary: UNCHARTED: Legacy of Thieves Collection includes UNCHARTED 4: A Thief’s End and UNCHARTED: The Lost Legacy remastered for PS5™. Play as Nathan Drake and Chloe Frazer in their own standalone adventures as they are forced to confront their pasts and forge their own legacies.', 'https://static.metacritic.com/images/products/games/7/cc80ae9984fed15d4a299abe94912286-98.jpg', 'Naughty Dog', 'T', 'Action Adventure', 87, 8.7, 'PlayStation Studios');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Destiny 2: The Witch Queen', 'Summary: The Definitive Destiny Campaign. Delve into Savathûn’s Throne World to uncover the mystery of how she and her Lucent Hive stole the Light. Learn the secrets to crafting new weapons, the new Glaive, and survive the truth within her web of lies. New Destination. A twisted wonderland of corruption and splendor, Savathûn’s Throne World plays host to a fragile balance of power. From her palace to the swamp, all that she hides can be found here. Weapon Crafting. Create custom weaponry with unique mod, shader, and stat combinations. Master the new Glaive weapon type and unleash powerful melee combos, projectile attacks, and a deployable energy shield.', 'https://static.metacritic.com/images/products/games/6/03c87b89bf6faeb5680914e064452967-98.jpg', 'Bungie', 'T', 'Action Shooter', 87, 8.0, 'Bungie');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Inscryption', 'Summary: From the creator of Pony Island and The Hex comes the latest mind melting, self-destructing love letter to video games. Inscryption is an inky black card-based odyssey that blends the deckbuilding roguelike, escape-room style puzzles, and psychological horror into a blood-laced smoothie. Darker still are the secrets inscrybed upon the cards...', 'https://static.metacritic.com/images/products/games/8/f0f846fd2081cd64d7063a5f4c64dd1f-98.jpg', 'Daniel Mullins Games', 'M', 'Strategy', 87, 8.1, 'Devolver Digital');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Chicory: A Colorful Tale', 'Summary: A Painting Adventure: You\'re a dog wielding a magic paintbrush! Use the power of art to explore, solve puzzles, help your animal friends and restore color to the world in this top-down adventure game.\nExplore the Picnic Province, and draw on anything!\nManipulate the environment with your paint and solve puzzles!', 'https://static.metacritic.com/images/products/games/5/e0c8b190d32f19b9ba34ab39b8e6dff5-98.jpg', 'Greg Lobanov', 'E', 'Adventure', 87, 7.0, 'Finji');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Tales of Arise', 'Summary: Challenge the Fate That Binds You. On the planet Dahna, reverence has always been given to Rena, the planet in the sky, as a land of the righteous and divine. Stories handed down for generations became truth and masked reality for the people of Dahna. For 300 years, Rena has ruled over Dahna, pillaging the planet of its resources and stripping people of their dignity and freedom.', 'https://static.metacritic.com/images/products/games/0/2f626a690293f8e2c59865c7cb7e337b-98.jpg', 'Bandai Namco Games', 'T', 'Role-Playing', 87, 8.6, 'Bandai Namco Games');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Crash Bandicoot 4: It\'s About Time', 'Summary: It\'s About Time - for a brand-wumping new Crash Bandicoot game! Crash fourward into a time shattered adventure with your favorite marsupials. Neo Cortex and N. Tropy are back at it again and launching an all-out assault on not just this universe, but the entire multiverse! Crash and Coco are here to save the day by reuniting the four Quantum Masks and bending the rules of reality. New abilities? Check. More playable characters? Yep. Alternate dimensions? Obviously. Ridonkulous bosses? For sure. Same awesome sauce? You bet your sweet jorts. Wait, are they actually jorts? Not in this universe!', 'https://static.metacritic.com/images/products/games/9/5e5503b0e9f7be3a8e951272aae247db-98.jpg', 'Toys for Bob', 'E10+', 'Platformer', 86, 7.9, 'Activision');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Yakuza: Like A Dragon', 'Summary: RISE FROM ROCK BOTTOM - Ichiban Kasuga, a low-ranking grunt of a low-ranking yakuza family in Tokyo, faces an 18-year prison sentence after taking the fall for a crime he didn\'t commit. Never losing faith, he loyally serves his time and returns to society to discover that no one was waiting for him on the outside, and his clan has been destroyed by the man he respected most.', 'https://static.metacritic.com/images/products/games/0/d374cfaf334eb42013f97954c7e80e7e-98.jpg', 'Ryu ga Gotoku Studios', 'M', 'Role-Playing', 86, 8.1, 'Sega');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Cult of the Lamb', 'Summary: Start your own cult in a land of false prophets, venturing out into diverse and mysterious regions to build a loyal community of woodland worshippers and spread your Word to become the one true cult. BUILD YOUR FLOCK. Collect and use resources to build new structures, perform dark rituals to appease the gods, and give sermons to reinforce the faith of your flock. DESTROY THE NON-BELIEVERS. Explore a sprawling, randomly generated world, fight off hordes of enemies and defeat rival cult leaders in order to absorb their power and assert your cult\'s dominance. SPREAD YOUR WORD. Train your flock and embark on a quest to explore and discover the secrets of five mysterious regions. Cleanse the non-believers, spread enlightenment and perform mystical rituals on the journey to become the mighty lamb god.', 'https://static.metacritic.com/images/products/games/1/223bb44722886e091320f651df207ff3-98.jpg', 'Massive Monster', 'T', 'Action Adventure', 86, 6.2, 'Devolver Digital');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Tunic', 'Summary: TUNIC is an action adventure game about a tiny fox in a big world where you don\'t belong. Presented by Finji. Explore a land filled with lost legends, ancient powers, and ferocious monsters in TUNIC, an isometric action game about a small fox on a big adventure. Stranded on a mysterious beach, armed with only your own curiosity, you will confront colossal beasts, collect strange and powerful items, and unravel long-lost secrets.', 'https://static.metacritic.com/images/products/games/5/f497031c48d525c8e756c6ded95e52b5-98.jpg', 'ISOMETRICORP Games', 'E', 'Action Adventure', 86, 8.0, 'Finji');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Tactic Ogre: Reborn', 'Summary: Based on the 2010 release, the game features improved graphics and sound, as well as updated game design, bringing to life a new Tactics Ogre that remains true to its roots. Tactics Ogre veterans will experience a game that surpasses their fondest memories, while players new to Tactics Ogre will discover a game unlike any they\'ve ever played. Reborn and deeper than ever, the game enables players to immerse themselves in the world and intrigue of Tactics Ogre like never before. The Valerian Isles, jewels of the Obero Sea. Long a center of naval commerce, the people of the isles struggled throughout history for dominion over her shores. Finally there rose a man to put an end to this conflict: Dorgalua Oberyth. But history would know him as the \"Dynast-King.\" King Dorgalua strove to stamp out the hatred among the people of the isles, and for fully half a century, Valeria knew prosperity. Yet upon the king\'s death, civil war erupted anew as three factions vied for control: the Bakram, who comprised much of Valeria\'s nobility; the Galgastani, whose people made up the majority of the isles\' population; and the Walister, who numbered but few. The isles were soon divided between the Bakram and Galgastani, and an uneasy peace settled across the land. Yet none believed the calm would last...', 'https://static.metacritic.com/images/products/games/3/3b61758428e3a8d7b29757beaecb27f8-98.jpg', 'Square Enix', 'T', 'Strategy', 86, 5.6, 'Square Enix');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Returnal', 'Summary: Returnal transforms roguelike gameplay into a third-person shooter where players fight to survive a hostile planet that changes with every death. Players can switch instinctively between firing modes by using a single adaptive trigger and can get right back into the action after dying. PS5’s immersive 3D audio brings the alien world to life around the player, helping players navigate the intense positional combat.', 'https://static.metacritic.com/images/products/games/3/917155c153f3d6691b94fc08d3aad527-98.jpg', 'Housemarque', 'T', 'Action Shooter', 86, 7.3, 'PlayStation Studios');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Chivalry 2', 'Summary: Chivalry 2 is a multiplayer first person slasher inspired by epic medieval movie battles. Players are thrust into the action of every iconic moment of the era - from the thunder of cavalry charges, to storms of flaming arrows, sprawling castle sieges and more. Catapults tear the earth apart as players lay siege to castles, set fire to villages and slaughter filthy peasants in the return of grand Team Objective maps. Ride to war on horseback and claim glory by your blade. Are ye a heroic warrior, or a blood-soaked murderer? Keep fighting and gurgling out battlecries even when wounded, bleeding out and missing limbs. Enhanced player expression brings thousands of hilarious new voice-lines and deep character customization. A revamped, faster and more fluid combat system offers an expanded range of creative choices, allowing players to perfect their playstyle. Immersive sound and effects ensure every blow lands with the sickening thud of steel sinking into bone.', 'https://static.metacritic.com/images/products/games/6/99ebaff4bbf064899bae3d5936396d2a-98.jpg', 'Tom Banner Studios', 'M', 'Action', 85, 6.3, 'Deep Silver');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Return to Monkey Island', 'Summary: It\'s been many years since Guybrush Threepwood was last locked in a battle of wits with his nemesis, the zombie pirate LeChuck. His true love, Elaine Marley, has turned her focus away from governing and Guybrush himself is adrift and unfulfilled, having never found the Secret of Monkey Island. Hip, young pirate leaders led by Captain Madison have shuffled the old guard from power, Melee Island has taken a turn for the worse, and famed businessman Stan has been imprisoned for \'marketing-related crimes\'.', 'https://static.metacritic.com/images/products/games/1/bb85543877b4d55c872ad51c20119930-98.jpg', 'Terrible Toybox', 'E', 'Adventure', 85, 7.2, 'Devolver Digital');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Crusader Kings 2', 'Summary: Paradox Development Studio brings you the sequel to one of the most popular strategy games ever made. Crusader Kings III is the heir to a long legacy of historical grand strategy experiences and arrives with a host of new ways to ensure the success of your royal house.', 'https://static.metacritic.com/images/products/games/3/4f568956f98a9959c88eac9132de80a7-98.jpg', 'Lab42', 'T', 'Strategy', 85, 6.6, 'Paradox Interactive');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Marvel\'s Spider-Man: Miles Morales', 'Summary: The latest adventure in the Spider-Man universe builds on and expand Marvel’s Spider-Man through an all-new story. Players experience the rise of Miles Morales as he masters new powers to become his own Spider-Man. With PS5’s SSD, players can near-instantaneously fast-travel across Marvel’s New York City, or feel the tension of each one of Miles’s web-swings, punches, web shots, and venom blasts with the DualSense wireless controller’s haptic feedback. Highly-detailed character models and enhanced visuals across the game intensify the story of Miles Morales as he faces great, new challenges while learning to be his own Spider-Man.', 'https://static.metacritic.com/images/products/games/9/b98a1d69c467b0ad796ded383599eb72-98.jpg', 'Insomniac Games', 'T', 'Action Adventure', 85, 7.7, 'PlayStation Studios');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Control: Ultimate Edition', 'Summary: After a secretive agency in New York is invaded by an otherworldly threat, you become the new Director struggling to regain Control. This supernatural third-person action-adventure game will challenge you to master a combination of supernatural abilities, modifiable loadouts and reactive environments, while fighting through a deep and unpredictable world. Become the new Director struggling to regain Control.\nYou are Jesse Faden, a young woman with a troubled past. You become the new Director of the Bureau of Control Our frontline in researching and fighting against supernatural enemies like the Hiss threatening our very existence.', 'https://static.metacritic.com/images/products/games/6/18eee2fdc213d1dd441cfcdca0d27af9-98.jpg', 'Remedy Entertainment', 'M', 'Action Adventure', 85, 8.0, '505 Games');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Warframe', 'Summary: Set in the far reaches of outer space during a new Dark Age, WARFRAME introduces the Tenno, a race on the brink of extinction after being enslaved by the Grineer for centuries. Players enter WARFRAME on the cusp of the Grineer\'s victory over the Tenno until they begin to arm themselves with WARFRAMES - an ancient exo-skeletal technology only they can operate. Hidden within the Orokin Derelicts of a lost civilization, new WARFRAMES lie dormant and undiscovered. These artifacts are the Tenno\'s only hope for survival.', 'https://static.metacritic.com/images/products/games/0/f76b111fcc137f5120109909a7720f18-98.jpg', 'Digital Extremes', 'T', 'Action Shooter', 85, 7.7, 'Digital Extremes');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Death Stranding: Director\'s Cut', 'Summary: From legendary game creator Hideo Kojima comes a genre-defying experience, now expanded and remastered for the PlayStation 5 console in this definitive Director’s Cut. In the future, a mysterious event known as the Death Stranding has opened a doorway between the living and the dead, leading to grotesque creatures from the afterlife roaming the fallen world marred by a desolate society. Take on the trials of Sam Bridges with advanced combat, more character actions and a competitive ranking system for special player challenges.* Make use of additional weapons and vehicles, take on new enemy types and explore new locations such as the Firing Range and Racetrack, featuring extra missions and minigames. Experience an extended storyline through new missions in an expanded area.', 'https://static.metacritic.com/images/products/games/5/10195976cd50e4ab98b9580b9addbc7c-98.jpg', 'Kojima Productions', 'M', 'Action Adventure', 85, 7.2, 'PlayStation Studios');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Assassin\'s Creed Valhalla', 'Summary: Build your own Viking Legend. Become Eivor, a Viking raider raised to be a fearless warrior, and lead your clan from icy desolation in Norway to a new home amid the lush farmlands of ninth-century England. Find your settlement and conquer this hostile land by any means to earn a place in Valhalla. England in the age of the Vikings is a fractured nation of petty lords and warring kingdoms. Beneath the chaos lies a rich and untamed land waiting for a new conqueror. Will it be you? Write Your Viking Saga. Blaze your own path across England with advanced RPG mechanics. Fight brutal battles, lead fiery raids or use strategy and alliances with other leaders to bring victory. ', 'https://static.metacritic.com/images/products/games/4/c583cf0ba8e80f79804ec54352de5886-98.jpg', 'Ubisoft Montreal', 'M', 'Action Adventure', 84, 7.8, 'Ubisoft');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Hitman 3', 'Summary: Death Awaits\nHITMAN 3 is the dramatic conclusion to the World of Assassination trilogy and takes players around the world on a globetrotting adventure to sprawling sandbox locations. Agent 47 returns as a ruthless professional for the most important contracts of his entire career.', 'https://static.metacritic.com/images/products/games/2/481f3752b7117241d889292694a38165-98.jpg', 'Io Interactive', 'M', 'Action Adventure', 84, 8.0, 'Io Interactive');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Resident Evil Village', 'Summary: The next generation of survival horror rises in the form of Resident Evil Village, the eighth major entry in the Resident Evil series. With ultra-realistic graphics powered by the RE Engine, fight for survival as danger lurks around every corner. Years after the tragic events of Resident Evil 7 biohazard, Ethan Winters has started over with his wife Mia, finally living in peace and putting the past behind them. However, Chris Redfield, the legendary hero from previous Resident Evil games, suddenly disrupts their life, throwing a devastated Ethan into a new and twisted nightmare in search of answers.', 'https://static.metacritic.com/images/products/games/0/0bfeb6536401efce8d403ffde5b903cb-98.jpg', 'Capcom', 'M', 'Action Adventure', 84, 8.3, 'Capcom');
INSERT INTO `game` (`id`, `title`, `description`, `image_url`, `developer`, `rating`, `genre`, `metascore`, `user_score`, `publisher`) VALUES (DEFAULT, 'Astro\'s Playroom', 'Summary: Astro and his crew lead you on a magical introduction through PS5 in this fun platformer that comes pre-loaded on PS5. Explore four worlds, each based on PS5’s console components. Each area showcases innovative gameplay that taps into the new features of the PS5’s DualSense wireless controller.', 'https://static.metacritic.com/images/products/games/3/6f79c670d0720dcd3bed9c10dfc3195e-98.jpg', 'Team Asobi', 'E10+', 'Platformer', 83, 9.2, 'PlayStation Studios');

COMMIT;

